name: Eddie Cejvan
favicon: null
layout_spectrum: 0.5178911914117634
typography_spectrum: 0.5211321613751352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5366208821069449
  lightness: 0.5437278531026095
  saturation: 0.4799628413747996
  rhythmicContrast: 0.2770662058610469
purpose: []
