favicon: null
name: Eddie Cejvan
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4444444
  brandStrength: 0.5752688
  lightness: 0.2795699
  brandColors:
    - '#171515'
    - '#B3A489'
    - '#FFFEFF'
    - '#6E4A28'
    - '#E09130'
  rhythmicContrast: 0.3566308
typography_spectrum: 0.5949821
layout_spectrum: 0.5519713
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
